CREATE USER odin WITH PASSWORD 'password';

CREATE DATABASE odin;
GRANT ALL PRIVILEGES ON DATABASE odin TO odin;

ALTER DEFAULT PRIVILEGES IN SCHEMA public
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO tuUsuario;

\c odin;

CREATE TABLE IF NOT EXISTS users (
    id SERIAL PRIMARY KEY,
    username VARCHAR(50),
    password VARCHAR(50),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);